import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Peak Bound Journeys",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
				<nav>
					<div className="logo">
						Peak Bound Journeys
					</div>
					<div className="menu"></div>
				</nav>
        {children}
      </body>
    </html>
  )
}