import type { Metadata } from "next"
import "./globals.css"
import { MouseEventHandler } from "react"

export const metadata: Metadata = {
  title: "Peak Bound Journeys",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

	function handleMenuClick(e: MouseEventHandler<HTMLDivElement>) {
		e.target.style.display = 'none'
	}

  return (
    <html lang="en">
      <body className={`antialiased`}>
				<nav>
					<div className="logo">
						Peak Bound Journeys
					</div>
					<div className="menu-icon" onClick={ handleMenuClick }>
						<div className="menu-bar"></div>
						<div className="menu-bar"></div>
						<div className="menu-bar"></div>
					</div>
				</nav>
        {children}
      </body>
    </html>
  )
}